MERCHANT_STATUS_PENDING = "pending"
MERCHANT_STATUS_ACTIVE = "active"
MERCHANT_STATUS_REVOKED = "revoked"
MERCHANT_STATUS_DISABLED = "disabled"

AUTH_SOURCE_MANUAL_TOKEN = "manual_token"
AUTH_SOURCE_OAUTH = "oauth"

BINDING_STATUS_DRAFT = "draft"
BINDING_STATUS_APPROVED = "approved"
BINDING_STATUS_ARCHIVED = "archived"
